"""Create Phase 1 Database

Revision ID: b1e1dae06f70
Revises: 
Create Date: 2026-09-28 17:14:11.902358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e1dae06f70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(length=200), nullable=False),
    sa.Column('data_source', sa.String(length=200), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=True),
    sa.Column('retrieval_upload_date', sa.DateTime(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('raw_record_count', sa.Integer(), nullable=True),
    sa.Column('accepted_record_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('retrieval_date', sa.DateTime(), nullable=False),
    sa.Column('query_parameters', sa.Text(), nullable=True),
    sa.Column('reporting_year', sa.Integer(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('epa_facility_id', sa.String(length=50), nullable=False),
    sa.Column('facility_name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('source_category', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facilities_state'), ['state'], unique=False)

    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('epa_unit_id', sa.String(length=50), nullable=False),
    sa.Column('unit_type', sa.String(length=100), nullable=True),
    sa.Column('primary_fuel', sa.String(length=100), nullable=True),
    sa.Column('secondary_fuel', sa.String(length=100), nullable=True),
    sa.Column('operating_date', sa.Date(), nullable=True),
    sa.Column('retirement_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_facility_id'), ['facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_primary_fuel'), ['primary_fuel'], unique=False)

    op.create_table('annual_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=False),
    sa.Column('operating_time', sa.Float(), nullable=True),
    sa.Column('gross_load', sa.Float(), nullable=True),
    sa.Column('steam_load', sa.Float(), nullable=True),
    sa.Column('heat_input', sa.Float(), nullable=True),
    sa.Column('co2_mass', sa.Float(), nullable=True),
    sa.Column('so2_mass', sa.Float(), nullable=True),
    sa.Column('nox_mass', sa.Float(), nullable=True),
    sa.Column('so2_control', sa.String(length=100), nullable=True),
    sa.Column('nox_control', sa.String(length=100), nullable=True),
    sa.Column('pm_control', sa.String(length=100), nullable=True),
    sa.Column('program_code', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'reporting_year', name='unique_unit_reporting_year')
    )
    with op.batch_alter_table('annual_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annual_records_reporting_year'), ['reporting_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_annual_records_unit_id'), ['unit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annual_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annual_records_unit_id'))
        batch_op.drop_index(batch_op.f('ix_annual_records_reporting_year'))

    op.drop_table('annual_records')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_primary_fuel'))
        batch_op.drop_index(batch_op.f('ix_units_facility_id'))

    op.drop_table('units')
    op.drop_table('uploaded_files')
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facilities_state'))

    op.drop_table('facilities')
    op.drop_table('data_provenance')
    op.drop_table('datasets')
    # ### end Alembic commands ###
